name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature') || startsWith(github.head_ref, 'fix') || startsWith(github.head_ref, 'dependabot') }}
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Install dependencies
        run: go mod tidy
      - name: Linting
        run: go fmt ./cmd/ ./pkg/server/
  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - lint
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Install dependencies
        run: go mod tidy
      - name: Run Unit Tests
        run: go test ./pkg/server
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -tags jsoniter -o bin/mailer cmd/main.go
  push:
    name: Push
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.base_ref, 'main') }}
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        uses: docker/login-action@v3
        with:
          ecr: true
          logout: true
          registry: 976750617193.dkr.ecr.ap-south-1.amazonaws.com
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 976750617193.dkr.ecr.ap-south-1.amazonaws.com/wecoach-backend
          tags: type=sha
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
