name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  set-up:
    name: Set-Up
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature') || startsWith(github.head_ref, 'fix') || startsWith(github.head_ref, 'dependabot') }}
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Install dependencies
        run: go mod tidy
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - set-up
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Linting
        run: go fmt ./cmd/
  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - lint
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Run Unit Tests
        run: go test -race --covermode atomic ./pkg/**
        env:
          MAILER_ENVIRONMENT: test
          MAILER_SMTP_IDENTITY: ${{ secrets.MAILER_SMTP_IDENTITY }}
          MAILER_SMTP_USERNAME: ${{ secrets.MAILER_SMTP_USERNAME }}
          MAILER_SMTP_PASSWORD: ${{ secrets.MAILER_SMTP_PASSWORD }}
          MAILER_SMTP_HOST: ${{ secrets.MAILER_SMTP_HOST }}
          MAILER_SMTP_PORT: ${{ secrets.MAILER_SMTP_PORT }}
          MAILER_CONTACT_US_DEFAULT_RECIPIENT: ${{ secrets.MAILER_CONTACT_US_DEFAULT_RECIPIENT }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: unofficialopensource-knit/MailerService
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Build
        run: go build -tags jsoniter -o bin/mailer cmd/main.go
